[tools]
uv = "0.11.16"

[tasks]
build = """
for dir in */*/*; do
  if [ -f "$dir/ato.yaml" ]; then
    (cd "$dir" && pwd && uv run ato build) || exit 1
  fi
done
"""

validate = """
for dir in */*/*; do
  if [ -f "$dir/ato.yaml" ]; then
    (cd "$dir" && pwd && uv run ato validate) || exit 1
  fi
done
"""
