[tools]
uv = "0.11.16"

[tasks.build]
usage = 'arg "[ci]"'
run = """
# ato build

FROZEN=""

if [ "${usage_ci:-}" = "ci" ]; then
  FROZEN="--frozen"
fi

for dir in src/*/*/*; do
  if [ -f "$dir/ato.yaml" ]; then
    (cd "$dir" && pwd && uv run ato build $FROZEN) || exit 1
  fi
done
"""

[tasks.validate]
run = """
# ato validate

for dir in src/*/*/*; do
  if [ -f "$dir/ato.yaml" ]; then
    (cd "$dir" && pwd && uv run ato validate) || exit 1
  fi
done
"""
