[workspace]
resolver = "2"
members = [
    "lib",
    # "device/board/mk1/lite",
    "device/board/mk1/pro",
    # "device/board/mk1/x",
    # "device/pad/mk1/trio",
]

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "s"

# set this to false then run cargo build to see actual firmware size.
# firmware file exists in target/thumbv7em-none-eabihf/release/<binary>.
# defmt logs won't show link to source code when set to false.
debug = true
